services:
  postgres:
    image: postgres:16-alpine
    container_name: eventhub-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: eventhub_db
    ports:
      - "5432:5432"
    restart: unless-stopped